version: '3.8'
services:
  postgres-web:
    image: postgres:15
    container_name: postgres-web
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresweb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ps

  backend:
    image: backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DB_PASSWORD: "postgres"
      salt: "kfcpassword"
      PORT: "8000"
      JWT_SECRET: "KLJzxlcjzkxljcklasnndlasjd13"
    depends_on:
      - postgres-web
    networks:
      - ps

networks:
  ps:

volumes:
  postgres-data:
    driver: local  # Используем локальный драйвер для хранения данных
